version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    restart: always
  cloudflare_exporter:
    image: ghcr.io/lablabs/cloudflare_exporter
    container_name: cloudflare_exporter
    ports:
      - "9091:9091"
    environment:
      CF_API_TOKEN: "${CF_API_TOKEN}"
      CF_ZONES: "${CF_ZONE_ID}"
      LISTEN: ":9091"
    restart: unless-stopped


